### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by cailv** [songqiaohu/CADM-plus#2]
Hello, Senior Hu! I am a first-year doctoral student from the School of Computer Science at Jilin University. I recently read your paper titled “CADM+: Confusion-Based Learning Framework With Drift Detection and Adaptation for Real-Time Safety Assessment”, and I benefited a lot from the basic ideas of this paper. The email address in your paper has expired. My research direction is intrusion detection in the Internet of Vehicles. Many of your works have inspired me. At present, I plan to study the development of intrusion detection systems under the collaborative architecture of car, fog and cloud. I have studied the project carefully. I would like to ask if you still have the comparison algorithm code in the paper. Can you share it? I would like to have an in-depth exchange and study with my seniors! Looking forward to your reply and guidance!

**Comment by songqiaohu** [comment]
Thank you for your kind words and for taking the time to read our paper. Regarding the comparison method codes, we have summarized them into a framework and made them open-source. Please refer to https://github.com/liuzy0708/Awesome_OL for detailed information.

**Comment by songqiaohu** [comment]
> Hello, Senior Hu! I am a first-year doctoral student from the School of Computer Science at Jilin University. I recently read your paper titled “CADM+: Confusion-Based Learning Framework With Drift Detection and Adaptation for Real-Time Safety Assessment”, and I benefited a lot from the basic ideas of this paper. The email address in your paper has expired. My research direction is intrusion detection in the Internet of Vehicles. Many of your works have inspired me. At present, I plan to study the development of intrusion detection systems under the collaborative architecture of car, fog and cloud. I have studied the project carefully. I would like to ask if you still have the comparison algorithm code in the paper. Can you share it? I would like to have an in-depth exchange and study with my seniors! Looking forward to your reply and guidance!

https://github.com/songqiaohu/CADM-plus/issues/2#issue-2726220149

**Comment by songqiaohu** [comment]
> Thank you for your kind words and for taking the time to read our paper. Regarding the comparison method codes, we have summarized them into a framework and made them open-source. Please refer to https://github.com/liuzy0708/Awesome_OL for detailed information.

Thank you for your kind words and for taking the time to read our paper. Regarding the comparison method codes, we have summarized them into a framework and made them open-source. Please refer to https://github.com/liuzy0708/Awesome_OL for detailed information.

**Comment by songqiaohu** [comment]
> Hello, Senior Hu! I am a first-year doctoral student from the School of Computer Science at Jilin University. I recently read your paper titled “CADM+: Confusion-Based Learning Framework With Drift Detection and Adaptation for Real-Time Safety Assessment”, and I benefited a lot from the basic ideas of this paper. The email address in your paper has expired. My research direction is intrusion detection in the Internet of Vehicles. Many of your works have inspired me. At present, I plan to study the development of intrusion detection systems under the collaborative architecture of car, fog and cloud. I have studied the project carefully. I would like to ask if you still have the comparison algorithm code in the paper. Can you share it? I would like to have an in-depth exchange and study with my seniors! Looking forward to your reply and guidance!

Thank you for your kind words and for taking the time to read our paper. Regarding the comparison method codes, we have summarized them into a framework and made them open-source. Please refer to https://github.com/liuzy0708/Awesome_OL for detailed information.
